### ISSUE TITLE
Some ids don't in training data 

### ISSUE THREAD

**Issue by yt605155624** [google/WikipediaHomographData#2] opened 2020-08-06 06:15 UTC
Hi， I have find that some word ids don't in training data ,such as {'intimate_vrb', 'compact_vrb', 'job_bible', 'moped_vrb', 'elaborate_vrb', 'incense_vrb', 'addict_vrb', 'object_vrb', 'desert_vrb', 'subject_vrb'} ，could you please provide the complete training data ?

**Comment by kylebgorman** [comment] 2020-08-06 13:11
For some homographs, one pronunciation is much more common than another, so
we wouldn't even expect to see the other one in a sample of, say, 100 forms
of that homograph.

Won't fix as this is not a bug; this is just the nature of the data!

**Comment by kylebgorman** [comment] 2020-10-20 19:25
Closing for inactivity. If anyone wants to add a note to the README about this, I will welcome a PR. Here's the list of invariant homographs: `addict compact conglomerate consort desert elaborate entrance incense instrument interchange intimate job moped mouth object pigment row subject`.

**Closed as completed by kylebgorman** 2020-10-20 19:25 UTC
